metadata:
- appName: ''
  dataId: application.yml
  desc: 通用配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-gateway.yml
  desc: 网关配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-monitor.yml
  desc: 监控配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-system-biz.yml
  desc: 系统配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-sentinel-dashboard.yml
  desc: sentinel监控
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-xxl-job-admin.yml
  desc: xxl-job分布式定时器配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-rocketmq-dashboard
  desc: rocketmq监控面板配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-auth.yml
  desc: 认证中心配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-monitor-biz
  desc: 运维监控配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: dolphin-common-biz
  desc: 通用业务配置
  group: DEFAULT_GROUP
  type: yaml
