metadata:
- appName: ''
  dataId: transport.type
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.server
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.heartbeat
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.enableTmClientBatchSendRequest
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.enableRmClientBatchSendRequest
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.enableTcServerBatchSendResponse
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.rpcRmRequestTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.rpcTmRequestTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.rpcTcRequestTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.bossThreadPrefix
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.workerThreadPrefix
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.serverExecutorThreadPrefix
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.shareBossWorker
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.clientSelectorThreadPrefix
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.clientSelectorThreadSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.clientWorkerThreadPrefix
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.bossThreadSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.threadFactory.workerThreadSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.shutdown.wait
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.serialization
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: transport.compressor
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: service.vgroupMapping.default_tx_group
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: service.default.grouplist
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: service.enableDegrade
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: service.disableGlobalTransaction
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.asyncCommitBufferLimit
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.lock.retryInterval
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.lock.retryTimes
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.lock.retryPolicyBranchRollbackOnConflict
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.reportRetryCount
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.tableMetaCheckEnable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.tableMetaCheckerInterval
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.sqlParserType
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.reportSuccessEnable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.sagaBranchRegisterEnable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.sagaJsonParser
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.rm.tccActionInterceptorOrder
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.commitRetryCount
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.rollbackRetryCount
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.defaultGlobalTransactionTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.degradeCheck
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.degradeCheckAllowTimes
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.degradeCheckPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.tm.interceptorOrder
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.dataValidation
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.logSerialization
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.onlyCareUpdateColumns
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.undo.logSaveDays
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.undo.logDeletePeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.logTable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.compress.enable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.compress.type
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: client.undo.compress.threshold
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: tcc.fence.logTableName
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: tcc.fence.cleanPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: log.exceptionRate
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.mode
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.lock.mode
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.session.mode
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.dir
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.maxBranchSessionSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.maxGlobalSessionSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.fileWriteBufferCacheSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.flushDiskMode
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.file.sessionReloadReadSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.datasource
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.dbType
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.driverClassName
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.url
  desc: ''
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.user
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.password
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.minConn
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.maxConn
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.globalTable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.branchTable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.distributedLockTable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.queryLimit
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.lockTable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.db.maxWait
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.mode
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.single.host
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.single.port
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.maxConn
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.minConn
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.maxTotal
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.database
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: store.redis.queryLimit
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.recovery.committingRetryPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.recovery.asynCommittingRetryPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.recovery.rollbackingRetryPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.recovery.timeoutRetryPeriod
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.maxCommitRetryTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.maxRollbackRetryTimeout
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.rollbackRetryTimeoutUnlockEnable
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.distributedLockExpireTime
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.session.branchAsyncQueueSize
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: server.session.enableBranchAsyncRemove
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: metrics.enabled
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: metrics.registryType
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: metrics.exporterList
  group: SEATA_GROUP
  type: text
- appName: ''
  dataId: metrics.exporterPrometheusPort
  group: SEATA_GROUP
  type: text
